### ISSUE TITLE
Create new Docker images and push to DocherHub

### ISSUE THREAD

**Issue by marijanbeg** [fangohr/oommf#13]
New Docker images should be created for:

1. Clean OOMMF without DMI extensions
2. OOMMF with DMI extensions

They are going to be in the same repository on DockerHub and the question is what should be the tags. Maybe `joommf/oommf:clean` and `joommf/oommf:extended (or with_extensions)`

**Comment by fangohr** [comment]
Update from discussion today: let's have one main (default) image which includes the extensions.

**Comment by marijanbeg** [comment]
In `Dockerfile` we had `COPY . oommf/`. This can only be used for testing when `oommf` repository is already cloned to Travis. Because of that, two Dockerfiles are created. One in the top level of repository and another in `docker/` directory. The one in `docker/` directory we are going to use to build images and push them to DockerHub. Docker image is now updated: https://cloud.docker.com/swarm/joommf/repository/docker/joommf/oommf/general
