### ISSUE TITLE
2.0a1

### ISSUE THREAD

**Issue by minrk** [fangohr/oommf#15]
There's a new 2.0a1 release of oommf. 2.0a0 doesn't build on recent macOS due to use of long-deprecated `panic` from tcl which collides with a system symbol of the same name. This is fixed in 2.0a1.

**Comment by akosmel** [comment]
Dear Hans, 
Thank you for sharing. I tried on my Mac osx, but I have this panic message  
2.0a1 panic:
Tk initialization error:

no display name and no $DISPLAY environment variable

I will be grateful for your help.

**Comment by fangohr** [comment]
Habe you got X installed? OOMMF needs an X display to open its GUI.
