### ISSUE TITLE
DMI extension

### ISSUE THREAD

**Issue by code-whale** [fangohr/oommf#19]
I tried to add the dmi extension according to the instructions in the windows system, but when I added the file and rerun the oommf Times error, when I wanted to add DMI, I simulated that I needed to add the DMI parameter in ubermag, but there was no DMI module in the oommf I installed. What should I do now? my oommf has failed to run.
![image](https://user-images.githubusercontent.com/61874432/86356522-f76a1280-bc9e-11ea-9aac-fd53b98ae752.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, you cannot add an extension to windows without compiling OOMMF. This is the intrinsic difficulty of using OOMMF on Windows.

The only way we can help with this problem is to use docker.

**Comment by code-whale** [comment]
Dear Marijan Beg,
Thank you for your patient answer. I have reinstalled oommf to solve this problem. I have tried to use docker before. 
Unfortunately, my version of Windows10 does not allow me to use it. I will try to install a virtual machine.
