### ISSUE TITLE
Move CI to travis.com / github workflows?

### ISSUE THREAD

**Issue by fangohr** [fangohr/oommf#21]

**Comment by marijanbeg** [comment]
This is now done in PR #25. There are two workflows:

1. `on-ubuntu-latest.yml`: Installs and tests OOMMF on ubuntu-latest - no Docker.
2. `in-docker.yml`:  Installs and tests OOMMF inside Docker container

- Most of the commands are in `Makefile`.
- `.travis.yml` is removed.

Things to review/do before closing:

- I am still not happy with Makefile target names and workflow names.
- Should we remove `on-ubuntu-latest.yml`?
- Remove Travis from Webhooks.

**Comment by marijanbeg** [comment]
Dockerfile is now based on Ubuntu 20.04.

**Comment by fangohr** [comment]
Done with PR #25 - thanks Marijan.
