### ISSUE TITLE
error: more undefined references to `std::__throw_bad_array_new_length()' follow

### ISSUE THREAD

**Issue by keyplay** [fangohr/oommf#38]
Hi, I try building OOMMF from source, but it report the following error after running **make build**: /usr/bin/ld: linux-x86_64/cgevolve.o:cgevolve.cc:(.text+0x7679): more undefined references to `std::__throw_bad_array_new_length()' follow

**Comment by fangohr** [comment]
Hi @keyplay - I don't know what goes wrong with your compilation. You would need to provide more information for others to be able to help you (linux distribution, versions, exact commands that have led to the error, full error message, etc). See also [here](https://fangohr.github.io/computing/smartquestion.html).

I have retriggered the execution of our pipelines today, for example at https://github.com/fangohr/oommf/actions/runs/3067188732/jobs/4953212729#step:3:1 where the compilation runs through nicely on Ubuntu 22.04.

I'll close this for now, assuming that the comment above helps you.

**Comment by lang-m** [comment]
Hi @keyplay, without knowing any details of your setup, so mostly a random guess. Make sure that you don't have any `conda` environments enabled (if you use `conda` at all, also make sure to disable the `base` environment) while compiling OOMMF.

**Comment by keyplay** [comment]
Hi @fangohr and @lang-m, thanks for your reply. After disabling conda environment, it reported that can't read "env(OOMMF_TCL_INCLUDE_DIR)": no such variable. 
I compiled the code on Ubuntu 22.04 with gcc 11.2.0 and tcl 8.6.12.

**Comment by keyplay** [comment]
The following is the screenshot of error message.
![image](https://user-images.githubusercontent.com/5894125/190970612-2dde1f51-4e35-4e6e-97d4-966d1851dd61.png)

**Comment by fangohr** [comment]
I am guessing that you have not installed the TCL header files, that come with the tcl-dev package. If so, make sure that you install all the dependencies as done in this Docker container https://github.com/fangohr/oommf/blob/master/docker/Dockerfile (see line 10).

**Comment by keyplay** [comment]
Thanks for your suggestion. I can compile the code nicely. After running **make-testall**, the following error messages are reported. I also tested it in the Docker container and got the same error message.
![image](https://user-images.githubusercontent.com/5894125/191079725-45023eb5-33f1-4ae1-b9f2-660a99c3f21c.png)

**Comment by lang-m** [comment]
This is the standard OOMMF output and here does not report any errors (only telling you to which file OOMMF would write errors, hence the word `errors`). As you can see from the output the first test (stdprob3) passed successfully (look for the lines `End "stdprob3.mif"` and `Boxsi run end`). We can't see the full output for the second test (stdprob4) but I would assume that it did also pass.
