### ISSUE TITLE
Dockerfiles in subdirectories

### ISSUE THREAD

**Issue by marijanbeg** [fangohr/oommf#8]
Why do we expect to have more than one Dockerfile and why do we need to have them in subdirectories?

**Comment by fangohr** [comment]
Reasons for subdirectories:

1. `docker` subdirectory

- tidy have all docker related files together

2. `docker/oommf` subdirectory level

- only to anticipate possible other Dockerfiles. We could have different docker files for different Ubuntu versions, or different flavours of OOMMF (with extension / without extensions), but it's not immediately clear.


We can change this if it helps. 

Does the question link to issue #6 ?

**Comment by rpep** [comment]
Maybe the Fenics or Bempp model of having a separate repository for different Dockerfiles (dev, stable) is a better way to go here.

On 11 Mar 2018, at 06:31, Hans Fangohr <notifications@github.com<mailto:notifications@github.com>> wrote:


Reasons for subdirectories:

  1.  docker subdirectory

  *   tidy have all docker related files together

  1.  docker/oommf subdirectory level

  *   only to anticipate possible other Dockerfiles. We could have different docker files for different Ubuntu versions, or different flavours of OOMMF (with extension / without extensions), but it's not immediately clear.

We can change this if it helps.

Does the question link to issue #6<https://github.com/fangohr/oommf/issues/6> ?

**Comment by marijanbeg** [comment]
Answers understood and issue closed.
